spring:
  application:
    name: AnswerHub
  data:
    redis:
      host: sh-crs-jlzh5uae.sql.tencentcdb.com
      port: 20573
      password: swx@20251022
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mysql
    url: jdbc:mysql://sh-cynosdbmysql-grp-8pcbibsk.sql.tencentcdb.com:28523/local_database
    username: root
    password: swx@20251022
logging:
  level:
    org:
      springframework:
        web:
          DEBUG
server:
  port: 8888